SELECT *FROM  EMPLOYEES;
SELECT *FROM LOCATIONS;
SELECT COUNT(*)FROM LOCATIONS;
SELECT COUNT(DEPARTMENT_ID)
FROM EMPLOYEES;
SELECT LOCATION_ID,count(*)
FROM DEPARTMENTS
GROUP BY LOCATION_ID
ORDER BY  2 DESC ;
SELECT REGION_ID, COUNT( * )FROM COUNTRIES
GROUP BY  REGION_ID
 ORDER BY COUNT(*)ASC;
SELECT DEPARTMENT_ID,SUM(SALARY),COUNT(*)FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

