SELECT *FROM DEPARTMENTS;
SELECT COUNT (*)FROM DEPARTMENTS;
SELECT *FROM LOCATIONS;
SELECT COUNT (*)FROM LOCATIONS;

SELECT COUNT(DEPARTMENT_ID)
FROM EMPLOYEES;
SELECT count(distinct FIRST_NAME )from EMPLOYEES;
