SELECT *FROM EMPLOYEES;
SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY ASC ;
SELECT  MAX(SALARY )FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY ASC)
WHERE ROWNUM< 4;

SELECT*FROM EMPLOYEES
WHERE SALARY=(SELECT  MAX(SALARY )FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY ASC)
                  WHERE ROWNUM < 4);



SELECT *FROM EMPLOYEES
WHERE SALARY =(SELECT  MAX(SALARY )FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY ASC)
               WHERE ROWNUM < 47);
SELECT* FROM DEPARTMENTS;