SELECT *FROM EMPLOYEES;
SELECT FIRST_NAME FROM EMPLOYEES;
SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;
SELECT  DISTINCT* FROM EMPLOYEES;
SELECT *FROM JOBS;
SELECT JOB_ID FROM JOBS;
select distinct job_id from jobs;







