select * from EMPLOYEES;
SELECT * FROM DEPARTMENTS;


select FIRST_NAME From EMPLOYEES;
select FIRST_NAME,LAST_NAME from EMPLOYEES;
select SALARY,EMAIL from EMPLOYEES;
select *from LOCATIONS;
SELECT COUNTRY_NAME,REGION_ID FROM COUNTRIES;
SELECT JOB_ID,JOB_TITLE FROM JOBS;
