SELECT * FROM EMPLOYEES;
SELECT *FROM EMPLOYEES
WHERE FIRST_NAME='David';
select *from EMPLOYEES
WHERE FIRST_NAME = 'David'AND LAST_NAME= 'lee';
SELECT FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES
WHERE FIRST_NAME='peter';
select*
from EMPLOYEES
WHERE SALARY>6000;
SELECT EMAIL
FROM EMPLOYEES
WHERE SALARY<5000;
SELECT*FROM EMPLOYEES
WHERE SALARY>7000 AND DEPARTMENT_ID =60;

