SELECT * FROM EMPLOYEES;
SELECT MAX (SALARY )FROM EMPLOYEES;
SELECT*
FROM EMPLOYEES
WHERE SALARY =2400;
SELECT *
FROM EMPLOYEES
WHERE SALARY=(SELECT MAX(SALARY)FROM EMPLOYEES);
SELECT MIN(SALARY)
FROM EMPLOYEES;
SELECT MAX (SALARY)
FROM EMPLOYEES
WHERE SALARY<24000;
SELECT*
FROM EMPLOYEES
WHERE SALARY =17000;
SELECT*
FROM EMPLOYEES
WHERE SALARY =(SELECT MAX(SALARY)FROM EMPLOYEES WHERE SALARY<24000);
SELECT ROUND (AVG(SALARY))FROM EMPLOYEES;
SELECT *
FROM EMPLOYEES
WHERE SALARY>6462;
SELECT*
FROM(SELECT*FROM EMPLOYEES ORDER BY SALARY DESC )
WHERE ROWNUM<6